library(tidyverse)
library(janitor)
library(dplyr)
library(readxl)
library(assertr)
library(stringr)

# Reading in data set 1, clean names, remove irrelevant columns, rename some columns for consistency
dataset1 <- read_excel("raw_data/candy_ranking_data/boing-boing-candy-2015.xlsx")
dataset1 <- select(dataset1, - contains("degrees_of_separation"), - contains("cash"),- contains("guess"), - contains("chalk"), - contains("degree_s_of_separation"), - contains("betty"), - contains("Taylor"), - contains("font"), - contains("imitation"), - contains("dress"), - contains("please"), - contains("squint"), - contains("cried"), - contains("friday"))
dataset1 <- dataset1 %>% pivot_longer(4:96, names_to = "candy_type")
dataset1 <- dataset1 %>% clean_names()
dataset1 <- dataset1 %>% rename(going_out = are_you_going_actually_going_trick_or_treating_yourself)
dataset1 <- dataset1 %>% rename(year = timestamp)
dataset1 <- dataset1 %>% rename(age = how_old_are_you)
dataset1 <- dataset1 %>% mutate(year = str_sub(year, start = 1, end = 4))



# Reading in data set 2, clean names, remove irrelevant columns, rename some columns for consistency
dataset2 <- read_excel("raw_data/candy_ranking_data/boing-boing-candy-2016.xlsx")
dataset2 <- select(dataset2, - contains("degrees_of_separation"), - contains("state"), - contains("cash"), - contains("ignore"), - contains("dvd"), - contains("guess"), - contains("betty"), - contains("degree_s_of_separation"), - contains("friday"), - contains("apple"), - contains("please"), - contains("dress"), - contains("font"))
dataset2 <- dataset2 %>% pivot_longer(6:103, names_to = "candy_type")
dataset2 <- dataset2 %>% clean_names()
dataset2 <- dataset2 %>% rename(going_out = are_you_going_actually_going_trick_or_treating_yourself)
dataset2 <- dataset2 %>% rename(gender = your_gender)
dataset2 <- dataset2 %>% rename(age = how_old_are_you)
dataset2 <- dataset2 %>% rename(country = which_country_do_you_live_in)
dataset2 <- dataset2 %>% rename(year = timestamp)
dataset2 <- dataset2 %>% mutate(year = str_sub(year, start = 1, end = 4))


# Reading in data set 3, clean names, remove irrelevant columns, rename some columns for consistency
dataset3 <- read_excel("raw_data/candy_ranking_data/boing-boing-candy-2017.xlsx")
colnames(dataset3) <- gsub("Q[0-9] |", "", colnames(dataset3))
dataset3 <- select(dataset3, - contains("housewives"), - contains("state"), - contains("Internal"), - contains("media"), - contains("other"), - contains("114"), - contains("dress"), - contains("day"), - contains("coordinates"), - contains("day"))
dataset3 <- dataset3 %>% pivot_longer(5:104, names_to = "candy_type")
dataset3 <- dataset3 %>% clean_names()
dataset3 <- dataset3 %>% mutate(year = 2017) %>% select(year, everything())
dataset3 <- dataset3 %>% mutate(year = as.character(year))
dataset3 <- dataset3 %>% rename(going_out = q1_going_out)
dataset3 <- dataset3 %>% rename(gender = q2_gender)
dataset3 <- dataset3 %>% rename(age = q3_age)
dataset3 <- dataset3 %>% rename(country = q4_country)
dataset3 <- dataset3 %>% mutate(candy_type = str_remove(candy_type, pattern = "[[|]]"))
dataset3 <- dataset3 %>% mutate(candy_type = trimws(candy_type, which = "left", whitespace = "[ \t\r\n]"))

# Bind datasets
  
candy <- dataset1 %>% bind_rows(dataset3) %>% bind_rows(dataset2)

# Set filter on age range
candy <- candy %>% mutate(age = as.numeric(age)) 
candy <- candy %>% filter(age >= 4 & age <= 100)

# Remove special characters from candy_type

candy <- candy %>% mutate(candy_type = str_replace_all(string = candy_type,
                                                       pattern = "[\\*\\[\\]]",
                                                       replacement = ""))

# Hard code countries

candy <- candy %>% mutate(country = str_replace_all(country, "america", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "America", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "'merica", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "Can", "Canada"))
candy <- candy %>% mutate(country = str_replace_all(country, "Canadaada", "Canada"))
candy <- candy %>% mutate(country = str_replace_all(country, "Canada`", "Canada"))
candy <- candy %>% mutate(country = str_replace_all(country, "Canadaae", "Canada"))
candy <- candy %>% mutate(country = str_replace_all(country, "endland", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "england", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "England", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "California", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USSA", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USAUSAUSA", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "usas", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USAA", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USA? Hard to tell anymore..", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USA!!!!!!", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USA! USA! USA!", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USA! USA!", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USA!", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USA USA USA!!!!", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USA USA USA USA", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USA USA USA", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USA", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "usa", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "United States of America", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "United States", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "U.S.", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "New Jersey", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "New York", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "North Carolina.", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "Pittsburgh", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "Scotland", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "españa", "Spain"))
candy <- candy %>% mutate(country = str_replace_all(country, "the best one - usa", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "Netherlands", "The Netherlands"))
candy <- candy %>% mutate(country = str_replace_all(country, "The republic of Cascadia", "cascadia"))
candy <- candy %>% mutate(country = str_replace_all(country, "The United States", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "The United States of America", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "The Yoo Ess of Aaayyyyyy", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "U S", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "u s a", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "U.K.", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "u.s.", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "U.s.", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "u.s.a.", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "U.S.A", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "U.K.", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "uk", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "Uk", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "Unied States.", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "unite states", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "United Kindom", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "United Kingdom", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "United kingdom", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "United Sates", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "United staes", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "United State", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "United Statea", "UK"))
candy <- candy %>% mutate(country = str_replace_all(country, "United Stated", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "united states", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "Units States", "US"))
candy <- candy %>% mutate(country = str_replace_all(country, "USd", "US"))

write_csv(candy, "candy.csv")
